server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restful_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: restful-service

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.evolution.restful.pojo

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/