server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: test-service
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.evolution.test.pojo

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/